#Nome da Actions:
name: Snake Game

#Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas. 
    - cron: "0 /5 * *"
workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Verifica o repositório.
- uses: actions/checkout@v2

      # Repositorio que será utilizado para gerar os arquivos.
- uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: itslucasmiranda  # Substitua com o seu nome de usuário no GitHub
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

      # Gerar o gif e svg, e salvar o status  
- run: |
        echo "snake-status=success" >> $GITHUB_ENV
        echo "gif-path=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
        echo "svg-path=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
# Para as atualizações.
name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: master
      force: true

# Publica no GitHub Pages
- uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

